### YamlMime:ManagedReference
items:
- uid: H.ApplicationBases.Module
  commentId: N:H.ApplicationBases.Module
  id: H.ApplicationBases.Module
  children:
  - H.ApplicationBases.Module.DefaultModuleOptions
  - H.ApplicationBases.Module.IDefaultModuleOptions
  langs:
  - csharp
  - vb
  name: H.ApplicationBases.Module
  nameWithType: H.ApplicationBases.Module
  fullName: H.ApplicationBases.Module
  type: Namespace
  assemblies:
  - H.ApplicationBases.Modules
references:
- uid: H.ApplicationBases.Module.DefaultModuleOptions
  commentId: T:H.ApplicationBases.Module.DefaultModuleOptions
  href: H.ApplicationBases.Module.DefaultModuleOptions.html
  name: DefaultModuleOptions
  nameWithType: DefaultModuleOptions
  fullName: H.ApplicationBases.Module.DefaultModuleOptions
- uid: H.ApplicationBases.Module.IDefaultModuleOptions
  commentId: T:H.ApplicationBases.Module.IDefaultModuleOptions
  parent: H.ApplicationBases.Module
  href: H.ApplicationBases.Module.IDefaultModuleOptions.html
  name: IDefaultModuleOptions
  nameWithType: IDefaultModuleOptions
  fullName: H.ApplicationBases.Module.IDefaultModuleOptions
- uid: H.ApplicationBases.Module
  commentId: N:H.ApplicationBases.Module
  href: H.html
  name: H.ApplicationBases.Module
  nameWithType: H.ApplicationBases.Module
  fullName: H.ApplicationBases.Module
  spec.csharp:
  - uid: H
    name: H
    href: H.html
  - name: .
  - uid: H.ApplicationBases
    name: ApplicationBases
    href: H.ApplicationBases.html
  - name: .
  - uid: H.ApplicationBases.Module
    name: Module
    href: H.ApplicationBases.Module.html
  spec.vb:
  - uid: H
    name: H
    href: H.html
  - name: .
  - uid: H.ApplicationBases
    name: ApplicationBases
    href: H.ApplicationBases.html
  - name: .
  - uid: H.ApplicationBases.Module
    name: Module
    href: H.ApplicationBases.Module.html
