### YamlMime:ManagedReference
items:
- uid: H.ApplicationBases.Identify
  commentId: N:H.ApplicationBases.Identify
  id: H.ApplicationBases.Identify
  children:
  - H.ApplicationBases.Identify.IdentifyApplicationBase
  langs:
  - csharp
  - vb
  name: H.ApplicationBases.Identify
  nameWithType: H.ApplicationBases.Identify
  fullName: H.ApplicationBases.Identify
  type: Namespace
  assemblies:
  - H.ApplicationBases.Identify
references:
- uid: H.ApplicationBases.Identify.IdentifyApplicationBase
  commentId: T:H.ApplicationBases.Identify.IdentifyApplicationBase
  href: H.ApplicationBases.Identify.IdentifyApplicationBase.html
  name: IdentifyApplicationBase
  nameWithType: IdentifyApplicationBase
  fullName: H.ApplicationBases.Identify.IdentifyApplicationBase
