### YamlMime:ManagedReference
items:
- uid: H.ApplicationBases.Modules
  commentId: N:H.ApplicationBases.Modules
  id: H.ApplicationBases.Modules
  children:
  - H.ApplicationBases.Modules.ModulesApplicationBase
  langs:
  - csharp
  - vb
  name: H.ApplicationBases.Modules
  nameWithType: H.ApplicationBases.Modules
  fullName: H.ApplicationBases.Modules
  type: Namespace
  assemblies:
  - H.ApplicationBases.Modules
references:
- uid: H.ApplicationBases.Modules.ModulesApplicationBase
  commentId: T:H.ApplicationBases.Modules.ModulesApplicationBase
  href: H.ApplicationBases.Modules.ModulesApplicationBase.html
  name: ModulesApplicationBase
  nameWithType: ModulesApplicationBase
  fullName: H.ApplicationBases.Modules.ModulesApplicationBase
