### YamlMime:ManagedReference
items:
- uid: H.Extensions.ApplicationBase
  commentId: N:H.Extensions.ApplicationBase
  id: H.Extensions.ApplicationBase
  children:
  - H.Extensions.ApplicationBase.ApplicationBase
  - H.Extensions.ApplicationBase.ApplicationBuilder
  langs:
  - csharp
  - vb
  name: H.Extensions.ApplicationBase
  nameWithType: H.Extensions.ApplicationBase
  fullName: H.Extensions.ApplicationBase
  type: Namespace
  assemblies:
  - H.Extensions.ApplicationBase
references:
- uid: H.Extensions.ApplicationBase.ApplicationBase
  commentId: T:H.Extensions.ApplicationBase.ApplicationBase
  href: H.Extensions.ApplicationBase.ApplicationBase.html
  name: ApplicationBase
  nameWithType: ApplicationBase
  fullName: H.Extensions.ApplicationBase.ApplicationBase
- uid: H.Extensions.ApplicationBase.ApplicationBuilder
  commentId: T:H.Extensions.ApplicationBase.ApplicationBuilder
  href: H.Extensions.ApplicationBase.ApplicationBuilder.html
  name: ApplicationBuilder
  nameWithType: ApplicationBuilder
  fullName: H.Extensions.ApplicationBase.ApplicationBuilder
